### ISSUE TITLE
Calendar Rewrite Plan

### ISSUE THREAD

**Issue by ncovercash** [ualibweb/ui-calendar#4]
This is for both `ui-calendar` and `mod-calendar`; there is no built-in way to replicate this issue on both so it's going here.

These will probably be broken down into sub-issues so their progress can be tracked more easily and put onto the kanban

### Requiring Investigation

- Determine preferred testing frameworks
  - FOLIO has gone through many testing frameworks over the years (biggest, cypress, jest, karma, nightmare, etc) and I would like to ensure we write tests with the preferred one
  - Various places of documentation all say each of these is the current preferred one, and I'm not sure which is the most recent/correct.
  - [x] **FE testing should be done with `rtl` and `jest`.** (#5)
  - [x] BE testing TBD; dependent upon Spring/RMB and other factors TBD first (https://github.com/ualibweb/mod-calendar/issues/3)
- [x] Find usage of the calendar APIs in other modules (https://github.com/ualibweb/mod-calendar/issues/4)
- [ ] Current permission scopes -- ensure they are what we need and can be mapped to the new structure (https://github.com/ualibweb/mod-calendar/issues/5)
- [ ] Determine the extent of audit logging required for GDPR compliance (https://github.com/ualibweb/mod-calendar/issues/6)
- [ ] Determine how API routes are versioned in the Spring Way (https://github.com/ualibweb/mod-calendar/issues/7)

### Determining Specifications

- [x] Create database schema (https://github.com/ualibweb/mod-calendar/issues/1)
- [x] Determine new API schema (subject to modification) (blocked by https://github.com/ualibweb/mod-calendar/issues/4)

### New Backend

- [x] Lay foundation for new backend (https://github.com/ualibweb/mod-calendar/issues/2)
  - [ ] Create example of starter Spring Boot module (#9)
- [ ] Implement old API routes as determined through investigation
- [ ] Plan new API routes
- [ ] Implement new API routes

### Backend Migration

- [ ] Write backend code to migrate from the current JSON database to a relational one
  - Not sure how this would work -- need to get in contact with someone more familiar
  - [ ] SQL to construct new schema
  - [ ] Java to parse old data and transform it into the new style
  - [ ] SQL to remove old schema

### Backend Tests

- [ ] Ensure each API route works properly
- [ ] Ensure that data conversion works correctly
- [ ] Fully document all new APIs and schema model

#### Admin Work

- [ ] Create updated mockups based on meeting discussions and improved UX ideas
  - [ ] Separated service point and calendar listings separate on the first pane
  - [ ] Drilldown on calendar or service point to modify/delete calendar or view info about historic/future service point calendars
  - [ ] Get approval (by SIGs?) before major development
- [ ] Update user stories

#### Features will likely be developed in (or close to) this order:

- [ ] Create calendar with standard hours
- [ ] Service point tabular listing
- [ ] Create calendar with exceptions
- [ ] Service point detailed listing
- [ ] Edit calendar
- [ ] Delete calendar
- [ ] Purge old calendars

### UI Testing

- [ ] TBD what tests specifically need to be made and how

### Documentation

- [ ] Add tutorials to https://docs.folio.com/ for:
  - [ ] Explaining new calendar/service point model
  - [ ] Creating a simple calendar
  - [ ] Applying a calendar to service points
  - [ ] Adding exceptions
  - [ ] Editing/deleting calendars
  - [ ] Viewing previous/historic calendars
  - [ ] Importance of purging calendars

**Comment by ualib-deploy** [comment]
Boy, that translation of JSON to sql DB seems like it will be really difficult. We need to find out how standardized the JSON is (schema anywhere to look at?), and then find some code to take the component parts of the JSON file, and shove them in to the appropriate corresponding SQL DB fields / table cells. Right?

**Comment by ualib-deploy** [comment]
And then we will need to provide the same API output that is expected from any call. I am hoping that this will be relatively easy.

**Comment by ncovercash** [comment]
It certainly does.  I have not investigated that part too in-depth, however, there may be some special API endpoints we can hook to ensure this works properly.

**Comment by sjturner-ua** [comment]
Should we update these items?

**Comment by ncovercash** [comment]
They're pretty up to date: currently working on the UI testing category
